display_name: "WeChat Article Writer"
name: wechat-article-writer
version: 2.3.3
description: End-to-end 微信公众号 article writing and publishing pipeline

requires:
  skills:
    - article-illustrator
  tools:
    - web_search
    - exec
    - subagents
    - browser
  env:
    - ZAI_API_KEY     # preferred: Z.AI image generation ($0.015/image)
    - OPENROUTER_API_KEY  # alternative: OpenRouter image fallback

triggers:
  # ── forge topic ──────────────────────────────────────────────────────────────
  - id: forge-topic-en
    mode: topic
    patterns:
      - "forge a topic about {subject}"
      - "forge topic {subject}"
      - "forge topic about {subject}"
      - "suggest wechat topics about {subject}"
      - "wechat topic ideas for {subject}"
    examples:
      - "forge a topic about AI coding assistants"
      - "forge topic about the latest ChatGPT update"
      - "suggest wechat topics about developer productivity"

  - id: forge-topic-zh
    mode: topic
    patterns:
      - "帮我选题：{subject}"
      - "帮我选题关于{subject}"
      - "公众号选题{subject}"
      - "给我{subject}的选题"
      - "选题{subject}"
    examples:
      - "帮我选题：大模型应用"
      - "公众号选题AI编程工具"
      - "给我技术周报的选题"

  # ── forge write ───────────────────────────────────────────────────────────────
  - id: forge-write-en
    mode: write
    patterns:
      - "forge article about {subject}"
      - "forge write {subject}"
      - "forge write about {subject}"
      - "write a wechat article about {subject}"
      - "create wechat article {subject}"
      - "create wechat article on {subject}"
      - "publish wechat article about {subject}"
    examples:
      - "forge article about the best AI tools in 2024"
      - "forge write about React Server Components"
      - "write a wechat article about open source LLMs"

  - id: forge-write-zh
    mode: write
    patterns:
      - "帮我写公众号文章：{subject}"
      - "帮我写公众号：{subject}"
      - "写一篇关于{subject}的公众号"
      - "全流程写作{subject}"
      - "写公众号文章{subject}"
    examples:
      - "帮我写公众号文章：Rust异步编程"
      - "写一篇关于AI画图工具的公众号"
      - "全流程写作本周大模型进展"

  # ── forge draft ───────────────────────────────────────────────────────────────
  - id: forge-draft-en
    mode: draft
    patterns:
      - "forge draft about {subject}"
      - "forge draft {subject}"
      - "draft a wechat article about {subject}"
      - "write wechat draft about {subject}"
    examples:
      - "forge draft about Python 3.13 new features"
      - "draft a wechat article about vector databases"

  - id: forge-draft-zh
    mode: draft
    patterns:
      - "帮我起草公众号文章：{subject}"
      - "帮我起草：{subject}"
      - "只写草稿，不发布：{subject}"
      - "只写草稿{subject}"
      - "起草一篇关于{subject}的公众号"
      - "起草{subject}的公众号"
      - "写草稿{subject}"
    examples:
      - "帮我起草公众号文章：本周AI新闻"
      - "起草一篇关于Claude 3的公众号"
      - "只写草稿，不发布：开源大模型对比"

  # ── forge publish ─────────────────────────────────────────────────────────────
  - id: forge-publish-en
    mode: publish
    patterns:
      - "forge publish {draft_id}"
      - "publish draft {draft_id}"
      - "send wechat draft {draft_id}"
      - "push draft {draft_id} to wechat"
    examples:
      - "forge publish ai-tools-20240217"
      - "publish draft tech-weekly-20240215"

  - id: forge-publish-zh
    mode: publish
    patterns:
      - "发布草稿{draft_id}"
      - "发布{draft_id}"
      - "推送草稿{draft_id}"
      - "forge publish {draft_id}"
    examples:
      - "发布草稿 ai-tools-20240217"
      - "发布 tech-weekly-20240215"

  # ── forge preview ─────────────────────────────────────────────────────────────
  - id: forge-preview-en
    mode: preview
    patterns:
      - "forge preview {draft_id}"
      - "preview draft {draft_id}"
      - "check draft {draft_id}"
      - "review wechat draft {draft_id}"
    examples:
      - "forge preview ai-tools-20240217"
      - "preview draft tech-weekly-20240215"

  - id: forge-preview-zh
    mode: preview
    patterns:
      - "预览草稿{draft_id}"
      - "预览{draft_id}"
      - "检查草稿{draft_id}"
    examples:
      - "预览草稿 ai-tools-20240217"

  # ── forge voice ───────────────────────────────────────────────────────────────
  - id: forge-voice-train-en
    mode: voice
    patterns:
      - "forge voice train"
      - "train my wechat writing voice"
      - "analyze my writing style for wechat"
      - "build voice profile from my articles"
    examples:
      - "forge voice train"
      - "train my wechat writing voice"

  - id: forge-voice-train-zh
    mode: voice
    patterns:
      - "训练我的写作风格"
      - "分析我的写作风格"
      - "分析我的公众号风格"
      - "建立声音档案"
      - "forge voice train"
    examples:
      - "训练我的写作风格"
      - "分析我的公众号风格"

  # ── forge status ──────────────────────────────────────────────────────────────
  - id: forge-status-en
    mode: status
    patterns:
      - "forge status"
      - "wechat article writer status"
      - "show wechat drafts"
      - "list wechat drafts"
      - "wechat pipeline status"
    examples:
      - "forge status"
      - "show wechat drafts"

  - id: forge-status-zh
    mode: status
    patterns:
      - "查看发布状态"
      - "公众号草稿状态"
      - "forge status"
      - "有哪些待发布的草稿"
    examples:
      - "查看发布状态"
      - "有哪些待发布的草稿"

# Negative patterns — do NOT trigger on these
negative_patterns:
  - "how does wechat work"
  - "what is wechat official account"
  - "wechat api documentation"
  - "forge a sword"
  - "forge metal"
  - "forge documents"    # "forge" meaning counterfeit

# Slot definitions
slots:
  subject:
    type: free_text
    description: The topic or subject of the article
    required: true
    capture: rest_of_utterance

  draft_id:
    type: identifier
    description: The draft slug or ID from ~/.wechat-article-writer/drafts/
    required: true
    pattern: "[a-z0-9][a-z0-9-]*"

# Configuration
config:
  wechat_secrets_path:
    type: path
    default: ~/.wechat-article-writer/secrets.json
    description: Path to WeChat API credentials file containing appid and appsecret

# Permissions (declared for security scanner transparency)
permissions:
  - exec: bash scripts/setup.sh (one-time setup — installs wenyan-cli, creates data dir)
  - exec: bash scripts/format.sh (markdown → WeChat HTML via wenyan-cli)
  - exec: python3 scripts/publish_via_api.py (WeChat Official Account API calls)
  - filesystem: read/write ~/.wechat-article-writer/ (drafts, config, voice profile)
  - filesystem: appends agent guidance to AGENTS.md and HEARTBEAT.md (setup.sh only, opt-in)
  - network: WeChat Official Account API (api.weixin.qq.com) — image upload and draft creation
  - network: web_search — topic research and fact-checking
  - browser: localhost:8899 — article preview before publishing

# Skill metadata
skill_metadata:
  invoke_as: skill
  max_concurrency: 2
  timeout_minutes: 30
  background_eligible: true   # long forge write runs can be backgrounded
