#!/bin/bash

# 小红书爬虫 - 快速命令汇总

echo "📱 小红书爬虫 - 快速命令"
echo "========================"
echo ""

echo "🔥 热门笔记抓取（无需登录）"
echo "-----------------------------"
echo "node scripts/hot-notes.js explore 1 20"
echo "node scripts/hot-notes.js food 1 20"
echo "node scripts/hot-notes.js fashion 1 20"
echo "node scripts/hot-notes.js tech 1 20"
echo "node scripts/hot-notes.js travel 1 20"
echo "node scripts/hot-notes.js beauty 1 20"
echo ""

echo "🌐 JSON 格式导出"
echo "-----------------------------"
echo "node scripts/hot-notes.js explore 1 20 json > notes.json"
echo "node scripts/hot-notes.js food 1 20 json > food.json"
echo "node scripts/hot-notes.js tech 1 20 json > tech.json"
echo ""

echo "🔑 Cookie 管理"
echo "-----------------------------"
echo "node scripts/status.js              # 查看状态"
echo "node scripts/get-cookie.js          # 获取 Cookie"
echo "node scripts/test-cookie.js         # 测试 Cookie"
echo "node scripts/test-cookie-detail.js  # 详细测试"
echo ""

echo "🔍 搜索功能（需登录）"
echo "-----------------------------"
echo "node scripts/search.js 手机测评 1 20"
echo "node scripts/search.js iPhone 15 2 10 json"
echo ""

echo "📄 笔记详情（需登录）"
echo "-----------------------------"
echo "node scripts/get-note.js 64bc4249000000001201df4d"
echo ""

echo "👤 用户信息（需登录）"
echo "-----------------------------"
echo "node scripts/get-user.js 用户 ID 20"
echo ""

echo "🛡️ 反爬机制"
echo "-----------------------------"
echo "node scripts/status.js              # 查看状态"
echo "node scripts/reset-counters.js      # 重置计数"
echo ""

echo "📊 批量获取"
echo "-----------------------------"
echo "# 获取所有分类"
echo "node scripts/hot-notes.js explore 1 20 json > explore.json"
echo "node scripts/hot-notes.js food 1 20 json > food.json"
echo "node scripts/hot-notes.js fashion 1 20 json > fashion.json"
echo "node scripts/hot-notes.js tech 1 20 json > tech.json"
echo "node scripts/hot-notes.js travel 1 20 json > travel.json"
echo "node scripts/hot-notes.js beauty 1 20 json > beauty.json"
echo ""

echo "✅ 当前状态"
echo "-----------------------------"
node scripts/status.js 2>/dev/null || echo "运行 'node scripts/status.js' 查看"
echo ""
