name: git-repo-to-book
version: 1.0.0
display_name: "Git Repo to Book"
description: >
  Write full-length technical books using multi-agent AI orchestration.
  Spawns parallel research, writing, and review agents. Produced an 88,000-word
  book in under 18 hours.
triggers:
  phrases:
    - write a book
    - book writing
    - write a technical book
    - multi-chapter
    - manuscript
    - 写书
    - 写一本书
    - book project
    - long-form document
  patterns:
    - "write .+ book"
    - "book about .+"
    - "technical book"
    - "multi.?agent.+writ"
owner: any
tools_required:
  - exec
  - sessions_spawn
  - read
  - write
tools_optional:
  - web_search
  - web_fetch
dependencies:
  python: ">=3.8"
  system:
    - git
  optional:
    - pandoc
