name: deepwiki-mcp
version: 1.0.0
display_name: "DeepWiki MCP"
description: >
  Query any public GitHub repository using DeepWiki's AI-powered documentation
  and Q&A service. No API key, no auth, free.
triggers:
  phrases:
    - deepwiki
    - look up in codebase
    - ask deepwiki
    - check the source
    - openclaw source
    - repo architecture
    - codebase question
  patterns:
    - "how does .+ work in"
    - "deepwiki"
    - "ask.*about.*repo"
owner: any
tools_required:
  - exec
dependencies:
  system:
    - bash
    - curl
    - python3
